import 'dotenv/config';
import {activityRouter} from './activity.js';
import {createNeuroLog} from './neurolog.js';
const neurolog=createNeuroLog();
import express from 'express';import mongoose from 'mongoose';import nodemailer from 'nodemailer';import path from 'node:path';import {fileURLToPath} from 'node:url';import {randomUUID,timingSafeEqual} from 'node:crypto';import {seed} from '../src/seed.js';import {validateData,reminderDue} from './validation.js';
const app=express();app.use(neurolog.middleware);app.use(express.json({limit:'2mb'}));
app.use('/api/activity',activityRouter(neurolog));
const guestSchema=new mongoose.Schema({id:{type:String,unique:true},name:String,designation:String,organization:String,email:String,phone:String,expertise:[String],roles:[String],available:Boolean,color:String},{_id:false,versionKey:false});
const eventSchema=new mongoose.Schema({id:{type:String,unique:true},name:String,date:String,time:String,venue:String,category:String,description:String,checklist:[{_id:false,id:String,text:String,done:Boolean}],assignments:[{_id:false,guestId:String,role:String,status:String,transport:{required:Boolean,pickup:String,drop:String,time:String,vehicle:String,driver:String,status:String}}]},{versionKey:false});
const Guest=mongoose.model('Guest',guestSchema),Event=mongoose.model('Event',eventSchema),Invitation=mongoose.model('Invitation',new mongoose.Schema({id:String,eventId:String,guestId:String,subject:String,body:String,sentAt:String,delivery:String,lastReminderAt:String},{versionKey:false}));
let connected=false;let snapshot=structuredClone(seed);
const smtp=()=>{if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)throw Error('SMTP is not configured');return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_PORT==='465',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}})};
const read=async()=>connected?{guests:await Guest.find().lean().then(xs=>xs.map(({_id,...x})=>x)),events:await Event.find().lean().then(xs=>xs.map(({_id,...x})=>x)),invitations:await Invitation.find().lean().then(xs=>xs.map(({_id,...x})=>x))}:snapshot;
const write=async data=>{validateData(data);if(connected){const session=await mongoose.startSession();try{await session.withTransaction(async()=>{for(const [model,rows] of [[Guest,data.guests],[Event,data.events],[Invitation,data.invitations]]){await model.deleteMany({}, {session});if(rows.length)await model.insertMany(rows,{session})}})}finally{await session.endSession()}}else snapshot=structuredClone(data)};
app.get('/api/health',(req,res)=>res.json({database:mongoose.connection.readyState===1?'MongoDB':process.env.MONGODB_URI?'unavailable':'memory',email:!!process.env.SMTP_HOST}));
app.use('/api',(req,res,next)=>{const expected=process.env.API_KEY;if(!expected)return res.status(503).json({error:'Set API_KEY in .env before using live mode'});const received=req.headers['x-api-key']||'';const a=Buffer.from(expected),b=Buffer.from(received);if(a.length!==b.length||!timingSafeEqual(a,b))return res.status(401).json({error:'Invalid API access key'});next()});
app.use('/api',(req,res,next)=>{if(process.env.MONGODB_URI&&(!connected||mongoose.connection.readyState!==1))return res.status(503).json({error:'MongoDB is unavailable. Check your Atlas connection string and network access, then restart the server.'});next()});
app.get('/api/data',async(req,res,next)=>{try{res.json(await read())}catch(e){next(e)}});
app.post('/api/data',async(req,res,next)=>{try{await write(req.body);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/invitations/send',async(req,res,next)=>{try{const{guestId,eventId,subject,body}=req.body;const d=await read(),g=d.guests.find(g=>g.id===guestId),e=d.events.find(e=>e.id===eventId);if(!g||!e?.assignments.some(a=>a.guestId===g.id)||!subject?.trim()||!body?.trim())throw Error('Guest assignment, subject and message are required');await smtp().sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:g.email,subject,text:body});const i={id:randomUUID(),guestId,eventId,subject,body,sentAt:new Date().toISOString(),delivery:'Sent'};if(connected)await Invitation.create(i);else snapshot.invitations.unshift(i);res.json(i)}catch(e){next(e)}});
let remindersRunning=false;
async function runReminders(){if(remindersRunning)return{sent:0};remindersRunning=true;let sent=0;try{const d=await read();for(const i of d.invitations){const e=d.events.find(e=>e.id===i.eventId),g=d.guests.find(g=>g.id===i.guestId),a=e?.assignments.find(a=>a.guestId===i.guestId);if(!g||!e||e.date<new Date().toISOString().slice(0,10)||a?.status!=='Invited'||!reminderDue(i))continue;await smtp().sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:g.email,subject:`Friendly reminder: ${i.subject}`,text:`Dear ${g.name},\n\nA friendly follow-up on our invitation. We would love to hear from you.\n\n${i.body}`});i.lastReminderAt=new Date().toISOString();if(connected)await Invitation.updateOne({id:i.id},{$set:{lastReminderAt:i.lastReminderAt}});else snapshot.invitations=snapshot.invitations.map(x=>x.id===i.id?i:x);sent++}return{sent}}finally{remindersRunning=false}}
app.post('/api/reminders/run',async(req,res,next)=>{try{res.json(await runReminders())}catch(e){next(e)}});
setInterval(()=>{if(process.env.SMTP_HOST)runReminders().catch(()=>{neurolog.log('Reminder delivery failed; check SMTP configuration',3);console.error('Reminder delivery failed');})},3600000).unref();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');app.use(express.static(path.join(root,'dist')));app.get('*',(req,res)=>res.sendFile(path.join(root,'dist','index.html')));app.use((err,req,res,next)=>{neurolog.log('Application operation failed; review request status and server configuration',3);res.status(400).json({error:err.message});});
if(process.env.MONGODB_URI){try{await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:5000});connected=true;if(await Guest.countDocuments()===0)await write(seed);neurolog.log('Database connection established');console.log('MongoDB connected')}catch(e){neurolog.log('Database connection unavailable; live workspace requests blocked',3);console.error('MongoDB unavailable; check MONGODB_URI and Atlas network access. Live workspace requests are blocked.')}}
setInterval(()=>neurolog.log(`Service heartbeat database=${connected?'mongodb':'memory'} queued_logs=${neurolog.pending()}`),30000).unref();
neurolog.log('GuestConnect service started');
app.listen(process.env.PORT||3001,'0.0.0.0',()=>console.log('GuestConnect API ready on port '+(process.env.PORT||3001)));

