import React from 'react';
import {ArrowRight,CheckCircle2,CalendarDays,ClipboardList,Mail,CarFront,Users,Plus,Trash2,MapPin} from 'lucide-react';
export function EventCommand({event,confirmed,pending,unarranged,transport,go}){
 const active=event.assignments.filter(a=>a.status!=='Declined'),ready=confirmed+transport.length-unarranged,total=active.length+transport.length,score=total?Math.round(ready/total*100):0;
 const days=Math.ceil((new Date(event.date+'T00:00:00')-new Date())/86400000);
 return <section className="event-dashboard"><div className="readiness-card card"><div className="section-top"><h3>Event readiness</h3><span className="outline-pill">{total?`${ready} / ${total} complete`:'No guests assigned'}</span></div><div className="gauge" role="img" aria-label={`Event readiness ${score} percent`}><svg viewBox="0 0 320 180">{Array.from({length:24},(_,i)=>{const angle=Math.PI+i*Math.PI/23,x=160+126*Math.cos(angle),y=150+126*Math.sin(angle);return <rect key={i} x={x-5} y={y-16} width="10" height="32" rx="5" fill={i<Math.round(score/100*24)?'#8270df':'#eeedf3'} transform={`rotate(${i*180/23-90} ${x} ${y})`}/>})}</svg><div className="gauge-value"><span className="gauge-symbol"><CheckCircle2 size={24}/></span><strong>{score}<small>%</small></strong><span>Ready to welcome</span></div></div><div className="readiness-breakdown"><div><span className="legend-dot purple"/><strong>{confirmed}</strong><span>Confirmed guests</span></div><div><span className="legend-dot mint"/><strong>{transport.length-unarranged}</strong><span>Arranged rides</span></div><div><span className="legend-dot yellow"/><strong>{pending+unarranged}</strong><span>To follow up</span></div></div></div><div className="event-summary card"><div className="section-top"><span className="eyebrow">SELECTED EVENT</span><span className="event-countdown">{days>0?`${days} days to go`:days===0?'Today':'Past event'}</span></div><h2>{event.name}</h2><p className="summary-description">{event.description}</p><div className="summary-meta"><span><CalendarDays size={17}/>{new Date(event.date+'T12:00').toLocaleDateString('en-IN',{day:'numeric',month:'long'})} · {event.time}</span><span><MapPin size={17}/>{event.venue}</span></div><div className="summary-actions"><button onClick={()=>go('Invitations')}><span className="action-icon"><Mail size={19}/></span><div><strong>{pending} pending responses</strong><span>Review your invitations</span></div><ArrowRight size={18}/></button><button onClick={()=>go('Transport')}><span className="action-icon yellow"><CarFront size={19}/></span><div><strong>{unarranged} rides to arrange</strong><span>Plan their campus journey</span></div><ArrowRight size={18}/></button></div><button className="text-btn" onClick={()=>go('Events')}>Manage this event <ArrowRight size={16}/></button></div></section>
}
export function PlanningTools({event,data,save,go}){
 const tasks=event.checklist||[];
 const addTask=e=>{e.preventDefault();const form=e.currentTarget,text=new FormData(form).get('task').trim();if(text)save({...data,events:data.events.map(x=>x.id===event.id?{...x,checklist:[...tasks,{id:crypto.randomUUID(),text,done:false}]}:x)}).then(ok=>{if(ok)form.reset()})};
 const changeTasks=next=>save({...data,events:data.events.map(x=>x.id===event.id?{...x,checklist:next}:x)});
 return <div className="planning-grid"><section className="card checklist"><div className="section-top"><div><h3><ClipboardList size={18}/>Preparation checklist</h3><p>Keep the small details from slipping through.</p></div><span className="outline-pill">{tasks.filter(t=>t.done).length}/{tasks.length}</span></div><div className="checklist-items">{tasks.length?tasks.map(t=><div className="checklist-row" key={t.id}><label className={t.done?'done':''}><input type="checkbox" checked={t.done} onChange={()=>changeTasks(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/>{t.text}</label><button className="icon-btn" aria-label={'Remove task '+t.text} onClick={()=>changeTasks(tasks.filter(x=>x.id!==t.id))}><Trash2 size={14}/></button></div>):<div className="checklist-empty">Add tasks for venue setup, guest kits, or team briefings.</div>}<form onSubmit={addTask}><input name="task" aria-label="New preparation task" placeholder="Add a preparation task…" maxLength={180} required/><button className="icon-btn" aria-label="Add task"><Plus size={18}/></button></form></div></section><section className="card insights"><div className="section-top"><div><h3><Users size={18}/>Network insights</h3><p>The people behind your campus events.</p></div></div><div className="insight-bars">{Object.entries(data.guests.flatMap(g=>g.expertise).reduce((out,t)=>({...out,[t]:(out[t]||0)+1}),{})).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([tag,count])=><div key={tag}><div><span>{tag}</span><strong>{count} guests</strong></div><div className="insight-track"><span style={{width:`${count/Math.max(data.guests.length,1)*100}%`}}/></div></div>)}</div><button className="text-btn" onClick={()=>go('Guest directory')}>Explore your network <ArrowRight size={15}/></button></section></div>
}
export function ActivityFeed({data}){const entries=data.invitations.slice(0,5);return <section className="card activity-feed"><div className="section-top"><div><h3>Recent outreach</h3><p>A record of your latest guest communications.</p></div><Mail size={20}/></div>{entries.length?<div className="feed-rows">{entries.map(i=><div key={i.id}><span className="feed-icon"><Mail size={16}/></span><div><strong>{data.guests.find(g=>g.id===i.guestId)?.name||'Guest'}</strong><p>{i.subject}</p></div><span>{i.delivery}<small>{new Date(i.sentAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></span></div>)}</div>:<div className="feed-empty"><Mail size={25}/><strong>No outreach yet</strong><p>Compose an invitation to start your activity history.</p></div>}</section>}
