import {activity,activityContext,installActivity} from './activity';
import {changeEvents} from './activitySchema';
installActivity();
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,CalendarDays,Mail,CarFront,FileText,Settings,ArrowUpRight,ArrowRight,Plus,Search,ChevronDown,ChevronLeft,ChevronRight,Bell,Check,Clock,MapPin,Download,X,Leaf,LogOut,CheckCircle2,AlertCircle,Send,Filter,Printer,Menu} from 'lucide-react';
import {seed,roles} from './seed';
import {validateData} from '../server/validation';
import './style.css';
import './modern.css';
import './premium.css';
import './reference.css';
import {EventCommand,PlanningTools,ActivityFeed} from './Enhancements';
const uid=()=>crypto.randomUUID();
const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const initials=n=>n.split(' ').filter(x=>!['Dr.','Prof.'].includes(x)).slice(0,2).map(x=>x[0]).join('');
const nav=[['Overview',LayoutDashboard],['Guest directory',Users],['Events',CalendarDays],['Invitations',Mail],['Transport',CarFront],['Reports',FileText]];
function App(){
 const [data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem('gc-data'))||structuredClone(seed)}catch{return structuredClone(seed)}}),[page,setPage]=useState('Overview'),[selected,setSelected]=useState('e1'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All expertise'),[future,setFuture]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[mode,setMode]=useState('demo'),[key,setKey]=useState(localStorage.getItem('gc-key')||'');
 const [roleFilter,setRoleFilter]=useState('All roles'),[lineupFilter,setLineupFilter]=useState('All statuses');
 useEffect(()=>{activityContext(page,mode);activity('navigation');},[page]);
 useEffect(()=>{activityContext(page,mode);activity('mode_changed');},[mode]);
 useEffect(()=>{activity('event_selected','event');},[selected]);
 useEffect(()=>{activity(modal?'dialog_opened':'dialog_closed',modal?.type||'application');},[modal?.type]);
 const event=data.events.find(e=>e.id===selected)||data.events[0], guests=data.guests;
 useEffect(()=>{localStorage.setItem('gc-data',JSON.stringify(data))},[data]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;const dialog=document.querySelector('.modal');const focusables=()=>[...dialog.querySelectorAll('button,input,textarea,select,a[href]')].filter(el=>!el.disabled);focusables()[0]?.focus();const handle=e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus()}},[!!modal]);
 const request=async(path,body)=>{const r=await fetch('/api'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-api-key':key},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok){activity('request_failed');throw Error(j.error||'Request failed');}activity('request_succeeded');return j};
 const save=async(next)=>{const saveTarget=modal?.type||'application';activity('save_started',saveTarget);try{validateData(next);if(mode==='live')await request('/data',next);for(const kind of changeEvents(data,next))activity(kind,kind.startsWith('event_')?'event':kind.startsWith('guest_')?'guest':kind.startsWith('transport_')?'transport':kind.startsWith('checklist_')?'checklist':kind.startsWith('assignment_')?'assign':kind.startsWith('invitation_')?'invite':'application');setData(next);activity('save_succeeded',saveTarget);return true}catch(e){activity('save_failed',saveTarget);setToast(e.message);return false}};
 const updateAssignment=(gid,patch)=>save({...data,events:data.events.map(e=>e.id===event.id?{...e,assignments:e.assignments.map(a=>a.guestId===gid?{...a,...patch}:a)}:e)});
 const go=p=>{setPage(p);setQuery('');setLineupFilter('All statuses');window.scrollTo({top:0,behavior:'instant'})};
 const notify=m=>setToast(m);
 const confirmed=event?.assignments.filter(a=>['Confirmed','Attended'].includes(a.status)).length||0;
 const pending=event?.assignments.filter(a=>a.status==='Invited').length||0;
 const transport=event?.assignments.filter(a=>a.transport.required&&a.status!=='Declined')||[];
 const unarranged=transport.filter(a=>a.transport.status==='Not Arranged').length;
 const upcoming=data.events.filter(e=>e.date>=new Date().toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date));
 const exportReport=async(type,guestOnly=false)=>{activity('export_started',type);try{const rows=(guestOnly?guests.map(g=>({Name:g.name,Organization:g.organization,Email:g.email,Expertise:g.expertise.join(', '),Roles:g.roles.join(', '),Available:g.available?'Yes':'No'})):data.events.flatMap(e=>e.assignments.map(a=>{const g=guests.find(g=>g.id===a.guestId);return{Event:e.name,Date:e.date,Guest:g?.name,Role:a.role,Confirmation:a.status,Transport:a.transport.required?a.transport.status:'Not required',Pickup:a.transport.pickup||'',Drop:a.transport.drop||'',Time:a.transport.time||'',Vehicle:a.transport.vehicle||'',Driver:a.transport.driver||''}})));
 if(type==='xlsx'){const {default:writeXlsx}=await import('write-excel-file/browser');const headers=Object.keys(rows[0]||{Guest:''});await writeXlsx([headers.map(h=>({value:h,fontWeight:'bold'})),...rows.map(r=>headers.map(h=>({value:String(r[h]??''),type:String})))],{fileName:'GuestConnect-report.xlsx'})}else{const{jsPDF}=await import('jspdf');const doc=new jsPDF();doc.setFontSize(20);doc.text('GuestConnect | Institutional report',14,20);let y=35;rows.forEach(row=>{const text=doc.splitTextToSize(Object.entries(row).map(([k,v])=>`${k}: ${v}`).join('  |  '),180);if(y+text.length*5>280){doc.addPage();y=20}doc.setFontSize(9);doc.text(text,14,y);y+=text.length*5+8});doc.save('GuestConnect-report.pdf')}activity('export_succeeded',type);notify('Report exported')}catch{activity('export_failed',type);notify('Report export failed. Please try again.')}};
 const sendInvite=async(form)=>{const g=guests.find(g=>g.id===form.guestId);let entry={id:uid(),eventId:event.id,guestId:g.id,subject:form.subject,body:form.body,sentAt:new Date().toISOString(),delivery:mode==='demo'?'Demo draft':'Sent'};try{if(mode==='live')entry=await request('/invitations/send',{...form,eventId:event.id});await save({...data,invitations:[entry,...data.invitations]});setModal(null);notify(mode==='demo'?'Invitation saved in demo mode. Connect SMTP to send email.':'Invitation email sent')}catch(e){notify(e.message)}};
 function guestForm(g){setModal({type:'guest',form:g?{...g,expertise:g.expertise.join(', ')}:{name:'',designation:'',organization:'',email:'',phone:'',expertise:'',roles:['Speaker'],available:true,color:'sage'}})}
 const Badge=({value})=><span className={'badge '+value.toLowerCase().replaceAll(' ','-')}><span/>{value}</span>;
 const Avatar=({g,small})=><span className={'avatar '+g.color+(small?' small':'')}>{initials(g.name)}</span>;
 const EventSelect=()=> <div className="select-wrap"><CalendarDays size={16}/><select aria-label="Select event" value={event?.id||''} onChange={e=>setSelected(e.target.value)}>{data.events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><ChevronDown size={14}/></div>;
 const guestTable=()=> <div className="table-scroll"><table><thead><tr><th>Guest</th><th>Event role</th><th>Confirmation</th><th>Transport</th><th></th></tr></thead><tbody>{event.assignments.filter(a=>{const g=guests.find(g=>g.id===a.guestId);return (lineupFilter==="All statuses"||a.status===lineupFilter)&&g?.name.toLowerCase().includes(query.toLowerCase())}).map(a=>{const g=guests.find(g=>g.id===a.guestId);return <tr key={a.guestId}><td><div className="person"><Avatar g={g} small/><div><strong>{g.name}</strong><span>{g.organization}</span></div></div></td><td>{a.role}</td><td><select className={'status-select '+a.status.toLowerCase()} aria-label={'Confirmation for '+g.name} value={a.status} onChange={e=>updateAssignment(g.id,{status:e.target.value})}>{['Invited','Confirmed','Declined','Attended'].map(s=><option key={s}>{s}</option>)}</select></td><td>{a.transport.required?<Badge value={a.transport.status}/>:<span className="muted">Not required</span>}</td><td><button className="icon-btn" aria-label={'View '+g.name} onClick={()=>setModal({type:'profile',guest:g})}><ArrowUpRight size={17}/></button></td></tr>})}</tbody></table></div>;
 return <div className="app"><header className="app-nav"><a className="brand" href="#" onClick={e=>{e.preventDefault();go('Overview')}}><span className="brand-icon"><Users size={22}/></span><span>guest<span className="brand-light">connect</span></span></a><nav aria-label="Main navigation">{nav.map(([n,I])=><button key={n} aria-current={page===n?'page':undefined} className={page===n?'active':''} onClick={()=>go(n)}><I size={18}/><span>{n==='Guest directory'?'Guests':n}</span></button>)}</nav><button className="icon-btn nav-settings" aria-label="Workspace settings" onClick={()=>go('Settings')}><Settings size={20}/></button></header><main><header className="topbar"><div className="welcome"><span className="account-avatar">AS</span><div><span>Your event workspace</span><strong>Welcome back, Alex</strong></div></div><div className="top-actions"><span className="today">Northview Institute <b>·</b> {new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</span><button className="bell icon-btn" aria-label="View attention items" onClick={()=>{go('Overview');notify(`${pending} guests awaiting a response · ${unarranged} rides need arranging`)}}><Bell size={19}/>{pending+unarranged>0&&<i/>}</button></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">CAMPUS EVENT MANAGEMENT</div><h1>{page==='Overview'?'Make every welcome count.':page}</h1><p>{({Overview:'Manage your guests, confirmations, and transport in one place.','Guest directory':'Search your campus network and find the right expertise.',Events:'Create events and manage guest assignments.',Invitations:'Send invitations and track guest responses.',Transport:'Coordinate pickups, drop-offs, vehicles, and drivers.',Reports:'Export guest records and event history.',Settings:'Connect your workspace to MongoDB and email.'})[page]}</p></div><button className="primary" onClick={()=>setModal({type:'event',form:{name:'',date:'',time:'09:00',venue:'',category:'Conference',description:'',assignments:[]}})}><Plus size={17}/>Create event</button></div>
 {page==='Overview'&&<><EventCommand event={event} confirmed={confirmed} pending={pending} unarranged={unarranged} transport={transport} go={go}/><div className="stats"><Stat title="Guests in your network" value={guests.length.toString().padStart(2,'0')} icon={Users} foot="A growing circle of connections" color="green"/><Stat title="Upcoming events" value={upcoming.length.toString().padStart(2,'0')} icon={CalendarDays} foot="Good things on the calendar" color="orange"/><Stat title="Awaiting confirmation" value={pending.toString().padStart(2,'0')} icon={Mail} foot="A friendly nudge goes a long way" color="purple"/><Stat title="Transport to arrange" value={unarranged.toString().padStart(2,'0')} icon={CarFront} foot="Let’s get their journey sorted" color="blue"/></div>{event.date>=new Date().toISOString().slice(0,10)&&new Date(event.date)-new Date()<7*86400000&&(pending+unarranged)>0&&<div className="deadline-alert"><AlertCircle size={17}/>Event is less than a week away: {pending} responses and {unarranged} transport arrangements need attention.</div>}<section className="card roster"><div className="section-top"><div><h3>Guest lineup</h3><p>Confirmation and transport status for each guest.</p></div><EventSelect/></div><div className="lineup-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search the guest lineup…"/><select aria-label="Filter confirmation status" value={lineupFilter} onChange={e=>setLineupFilter(e.target.value)}>{["All statuses","Invited","Confirmed","Declined","Attended"].map(x=><option key={x}>{x}</option>)}</select></div>{guestTable()}<div className="table-footer"><span>{event.assignments.length} guests · All the details, in one place</span><button className="text-btn" onClick={()=>go('Guest directory')}>View guest directory <ArrowRight size={15}/></button></div></section><PlanningTools event={event} data={data} save={save} go={go}/><div className="lower-grid"><section className="card next-events"><div className="section-top"><h3>On the horizon</h3><button className="text-btn" onClick={()=>go('Events')}>All events <ArrowUpRight size={15}/></button></div>{upcoming.filter(e=>e.id!==event.id).slice(0,2).map(e=><button className="upcoming-row" key={e.id} onClick={()=>{setSelected(e.id);go('Events')}}><span className="date-tile"><small>{new Date(e.date+'T12:00').toLocaleDateString('en',{month:'short'})}</small>{e.date.slice(-2)}</span><div><strong>{e.name}</strong><span>{e.category} <b>·</b> {e.assignments.length} guests</span></div><ArrowUpRight size={17}/></button>)}</section><section className="network-card"><Leaf size={27}/><div className="eyebrow">KEEP THE CONNECTION GOING</div><h3>Plan your next guest lineup</h3><p>Your past guests could be the perfect fit for what’s next.</p><button className="text-btn" onClick={()=>{go('Guest directory');setFuture(true)}}>Find your next guest <ArrowRight size={16}/></button><span className="decorative-ring"/></section></div></>}
 {page==='Overview'&&<ActivityFeed data={data}/>}
 {page==='Guest directory'&&<><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search name, organization, or expertise…"/><select aria-label="Filter expertise" value={filter} onChange={e=>setFilter(e.target.value)}><option>All expertise</option>{[...new Set(guests.flatMap(g=>g.expertise))].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter guest role" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option>All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select><label className="check-label"><input type="checkbox" checked={future} onChange={e=>setFuture(e.target.checked)}/>Available for future events</label><button className="primary" onClick={()=>guestForm()}><Plus size={16}/>Add guest</button></div><div className="guest-grid">{guests.filter(g=>(roleFilter==="All roles"||g.roles.includes(roleFilter))&&(!future||g.available)&&(filter==='All expertise'||g.expertise.includes(filter))&&[g.name,g.organization,...g.expertise].join(' ').toLowerCase().includes(query.toLowerCase())).map(g=><article className="card guest-card" key={g.id}><div className="section-top"><Avatar g={g}/><button className="icon-btn" aria-label={'Edit '+g.name} onClick={()=>guestForm(g)}><ArrowUpRight size={19}/></button></div><h3>{g.name}</h3><p>{g.designation}</p><strong className="org">{g.organization}</strong><div className="tags">{g.expertise.map(t=><span key={t}>{t}</span>)}</div><div className="guest-card-bottom"><span className={g.available?'available':'muted'}>{g.available?'● Available for outreach':'Not available'}</span><button className="text-btn" onClick={()=>setModal({type:'profile',guest:g})}>View profile <ArrowRight size={14}/></button></div></article>)}</div></>}
 {page==='Events'&&<><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search events…"/></div><div className="event-list">{data.events.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())).map(e=><section key={e.id} className={'card event-detail '+(event.id===e.id?'selected-event':'')}><div className="section-top"><div><span className="eyebrow">{e.category} · {date(e.date)}</span><h2>{e.name}</h2><p><MapPin size={14}/>{e.venue} · {e.time}</p></div><div className="button-row"><button className="secondary" onClick={()=>setModal({type:"event",form:{...e}})}>Edit event</button><button className="secondary" onClick={()=>setSelected(e.id)}>Manage guests <ArrowRight size={15}/></button></div></div>{event.id===e.id&&<><div className="toolbar compact"><button className="secondary" onClick={()=>setModal({type:'assign',form:{guestId:guests.find(g=>!e.assignments.some(a=>a.guestId===g.id))?.id||'',role:'Speaker'}})}><Plus size={16}/>Assign guest</button><button className="text-btn" onClick={()=>go('Invitations')}>Send invitations <Mail size={16}/></button></div>{guestTable()}</>}</section>)}</div></>}
 {page==='Invitations'&&<><div className="toolbar"><EventSelect/><button className="secondary" onClick={async()=>{if(mode==='demo'){notify('Follow-up reminders require live mode and SMTP.');return}try{const r=await request('/reminders/run',{});notify(`${r.sent} follow-up reminders sent`)}catch(e){notify(e.message)}}}><Clock size={16}/>Send due reminders</button></div><section className="card"><div className="section-top"><div><h3>Event invitations</h3><p>Edit your template before sending each invitation.</p></div><span className="outline-pill">{mode==='demo'?'Demo · emails not sent':'SMTP connected'}</span></div><div className="invitation-list">{event.assignments.map(a=>{const g=guests.find(g=>g.id===a.guestId);return <div className="invitation-row" key={g.id}><div className="person"><Avatar g={g} small/><div><strong>{g.name}</strong><span>{g.email}</span></div></div><Badge value={a.status}/><button className="secondary" onClick={()=>setModal({type:'invite',form:{guestId:g.id,subject:`Invitation to ${event.name}`,body:`Dear ${g.name},\n\nWe warmly invite you to join ${event.name} as our ${a.role} on ${date(event.date)} at ${event.time}, at ${event.venue}.\n\nWe would be delighted to welcome you to campus. Please reply to confirm your availability and any transport requirements.\n\nWarm regards,\nAlex Scott\nNorthview Institute`}})}><Mail size={15}/>{a.status==='Invited'?'Compose invitation':'Send message'}</button></div>})}</div></section><section className="card history-card"><h3>Invitation activity</h3>{data.invitations.length?data.invitations.map(i=><div className="activity-row" key={i.id}><Mail size={17}/><div><strong>{i.subject}</strong><p>{guests.find(g=>g.id===i.guestId)?.name} · {new Date(i.sentAt).toLocaleString()} · {i.delivery}</p></div></div>):<div className="empty"><Mail size={28}/><p>Your invitation history will appear here.</p></div>}</section></>}
 {page==='Transport'&&<><div className="toolbar"><EventSelect/><button className="secondary" onClick={()=>window.print()}><Printer size={16}/>Print logistics sheet</button></div><section className="card"><div className="section-top"><div><h3>Transport schedule</h3><p>{event.name} · {date(event.date)} · {transport.length} journeys</p></div><Badge value={unarranged?'Not Arranged':'Arranged'}/></div><div className="table-scroll"><table><thead><tr><th>Guest</th><th>Pickup → Drop</th><th>Time</th><th>Vehicle & driver</th><th>Status</th><th></th></tr></thead><tbody>{event.assignments.filter(a=>a.status!=='Declined').map(a=>{const g=guests.find(g=>g.id===a.guestId),t=a.transport;return <tr key={g.id}><td><div className="person"><Avatar g={g} small/><strong>{g.name}</strong></div></td><td>{t.required?<div className="route"><strong>{t.pickup||'Location pending'}</strong><span>→ {t.drop||'Drop pending'}</span></div>:'Not required'}</td><td>{t.time||'—'}</td><td><div className="route"><strong>{t.vehicle||'—'}</strong><span>{t.driver||''}</span></div></td><td>{t.required?<Badge value={t.status}/>:<span className="muted">—</span>}</td><td><button className="text-btn" onClick={()=>setModal({type:'transport',guest:g,form:{pickup:'',drop:'',time:'',vehicle:'',driver:'',...t}})}>Edit</button></td></tr>})}</tbody></table></div></section></>}
 {page==='Reports'&&<section className="card report-panel"><span className="report-icon"><FileText size={32}/></span><h2>Workspace reports</h2><p>Export your guest visit history, confirmation status, and transport details for institutional records.</p><div className="report-numbers"><div><strong>{guests.length}</strong><span>Guest profiles</span></div><div><strong>{data.events.length}</strong><span>Events</span></div><div><strong>{data.events.reduce((n,e)=>n+e.assignments.length,0)}</strong><span>Guest visits</span></div></div><div className="button-row"><button className="secondary" onClick={()=>exportReport("xlsx",true)}><Users size={17}/>Export guest directory</button><button className="primary" onClick={()=>exportReport('xlsx')}><Download size={17}/>Export Excel</button><button className="secondary" onClick={()=>exportReport('pdf')}><Download size={17}/>Export PDF</button></div></section>}
 {page==='Settings'&&<section className="card settings-panel"><h3>Workspace connection</h3><p>Demo mode saves your data in this browser. Live mode uses the Express API and configured MongoDB database.</p><label>API access key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Key from your server .env"/></label><div className="button-row"><button className="primary" onClick={async()=>{try{localStorage.setItem('gc-key',key);const d=await request('/data');setData(d);setMode('live');notify('Connected to live workspace')}catch(e){notify(e.message)}}}>Connect live workspace</button><button className="secondary" onClick={()=>{setMode('demo');notify('Demo mode enabled')}}>Use demo mode</button></div><p className="connection-state">Current mode: <strong>{mode}</strong></p><h3>Email & reminders</h3><p>Configure SMTP_HOST, SMTP_USER, SMTP_PASS, and MAIL_FROM in .env. Live reminders run hourly for invitations unanswered for three days.</p></section>}
 <footer className="page-footer"><span>Thoughtfully connected. Seamlessly welcomed.</span><span><span className="mode-dot"/>{mode==='demo'?'Demo workspace · saved locally':'Live workspace'} <b>·</b> GuestConnect</span></footer></div></main>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={modal.type+' details'} onClick={e=>e.stopPropagation()}><button className="modal-close icon-btn" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button>{modal.type==='profile'?<><Avatar g={modal.guest}/><h2>{modal.guest.name}</h2><p>{modal.guest.designation} · {modal.guest.organization}</p><p>{modal.guest.email}<br/>{modal.guest.phone}</p><div className="tags">{[...modal.guest.roles,...modal.guest.expertise].map(t=><span key={t}>{t}</span>)}</div><h3>Campus visit history</h3>{data.events.filter(e=>e.assignments.some(a=>a.guestId===modal.guest.id)).map(e=><div className="visit" key={e.id}><strong>{e.name}</strong><p>{date(e.date)} · {e.assignments.find(a=>a.guestId===modal.guest.id).role} · {e.assignments.find(a=>a.guestId===modal.guest.id).status}</p></div>)}<button className="primary" onClick={()=>guestForm(modal.guest)}>Edit profile</button></>:<><div className="eyebrow">GUESTCONNECT WORKSPACE</div><h2>{({guest:modal.form.id?'Edit guest':'A new connection',event:modal.form.id?'Edit event':'Create an event',assign:'Add to the guest lineup',invite:'A thoughtful invitation',transport:'Plan their journey'})[modal.type]}</h2><form onSubmit={async e=>{e.preventDefault();const f=modal.form;let ok=true;if(modal.type==='guest'){const g={...f,id:f.id||uid(),expertise:f.expertise.split(',').map(s=>s.trim()).filter(Boolean)};ok=await save({...data,guests:f.id?guests.map(x=>x.id===f.id?g:x):[...guests,g]})}if(modal.type==='event'){ok=await save({...data,events:f.id?data.events.map(x=>x.id===f.id?f:x):[...data.events,{...f,id:uid()}]})}if(modal.type==='assign'){ok=await save({...data,events:data.events.map(e=>e.id===event.id?{...e,assignments:[...e.assignments,{...f,status:'Invited',transport:{required:false,status:'Not Arranged'}}]}:e)})}if(modal.type==='transport'){ok=await updateAssignment(modal.guest.id,{transport:f})}if(modal.type==='invite'){await sendInvite(f);return}if(ok){setModal(null);notify('Saved successfully')}}}>
 {modal.type==='guest'&&<><Field modal={modal} setModal={setModal} name="name" label="Full name" required/><div className="form-grid"><Field modal={modal} setModal={setModal} name="designation" label="Designation" required/><Field modal={modal} setModal={setModal} name="organization" label="Organization" required/></div><div className="form-grid"><Field modal={modal} setModal={setModal} name="email" label="Email" type="email" required/><Field modal={modal} setModal={setModal} name="phone" label="Phone"/></div><Field modal={modal} setModal={setModal} name="expertise" label="Expertise (comma separated)"/><label>Role tags<div className="role-options">{roles.map(r=><label key={r}><input type="checkbox" checked={modal.form.roles.includes(r)} onChange={e=>setModal({...modal,form:{...modal.form,roles:e.target.checked?[...modal.form.roles,r]:modal.form.roles.filter(x=>x!==r)}})}/>{r}</label>)}</div></label><label className="check-label"><input type="checkbox" checked={modal.form.available} onChange={e=>setModal({...modal,form:{...modal.form,available:e.target.checked}})}/>Available for future events</label></>}
 {modal.type==='event'&&<><Field modal={modal} setModal={setModal} name="name" label="Event name" required/><div className="form-grid"><Field modal={modal} setModal={setModal} name="date" label="Event date" type="date" required/><Field modal={modal} setModal={setModal} name="time" label="Start time" type="time" required/></div><Field modal={modal} setModal={setModal} name="venue" label="Venue" required/><Field modal={modal} setModal={setModal} name="category" label="Event type" required/><Field modal={modal} setModal={setModal} name="description" label="Description" multiline/></>}
 {modal.type==='assign'&&<><label>Guest<select required value={modal.form.guestId} onChange={e=>setModal({...modal,form:{...modal.form,guestId:e.target.value}})}><option value="">Choose a guest</option>{guests.filter(g=>!event.assignments.some(a=>a.guestId===g.id)).map(g=><option value={g.id} key={g.id}>{g.name} · {g.organization}</option>)}</select></label><label>Event role<select value={modal.form.role} onChange={e=>setModal({...modal,form:{...modal.form,role:e.target.value}})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label></>}
 {modal.type==='invite'&&<><p>To: {guests.find(g=>g.id===modal.form.guestId)?.email}</p><Field modal={modal} setModal={setModal} name="subject" label="Subject" required/><Field modal={modal} setModal={setModal} name="body" label="Invitation message" multiline required/><p className="muted">{mode==='demo'?'Demo mode: saves a draft; does not send email.':'This message will be sent through your configured SMTP server.'}</p></>}
 {modal.type==='transport'&&<><p>{modal.guest.name}</p><label className="check-label"><input type="checkbox" checked={modal.form.required} onChange={e=>setModal({...modal,form:{...modal.form,required:e.target.checked}})}/>Transport required</label>{modal.form.required&&<><Field modal={modal} setModal={setModal} name="pickup" label="Pickup location" required/><Field modal={modal} setModal={setModal} name="drop" label="Drop location" required/><Field modal={modal} setModal={setModal} name="time" label="Pickup time" type="time" required/><Field modal={modal} setModal={setModal} name="vehicle" label="Vehicle / registration"/><Field modal={modal} setModal={setModal} name="driver" label="Driver name & contact"/><label>Status<select value={modal.form.status} onChange={e=>setModal({...modal,form:{...modal.form,status:e.target.value}})}>{['Not Arranged','Arranged','Completed'].map(s=><option key={s}>{s}</option>)}</select></label></>}</>}
 <div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>Cancel</button><button className="primary" type="submit">{modal.type==='invite'?<><Send size={16}/>{mode==='demo'?'Save demo invitation':'Send invitation'}</>:'Save '+({guest:'guest',event:'event',assign:'assignment',transport:'journey'})[modal.type]}</button></div></form></>}</section></div>}
 </div>
}
function Stat({title,value,icon:Icon,foot,color}){return <section className="card stat"><div><span>{title}</span><span className={'stat-icon '+color}><Icon size={20}/></span></div><strong>{value}</strong><p>{foot}</p></section>}
function SearchBox({value,onChange,placeholder}){return <div className="search-box"><Search size={17}/><input aria-label="Search" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
function Field({modal,setModal,name,label,type='text',required,multiline}){const props={name,value:modal.form[name]||'',required,onChange:e=>setModal({...modal,form:{...modal.form,[name]:e.target.value}})};return <label>{label}{multiline?<textarea rows={name==='body'?10:3} {...props}/>:<input type={type} {...props}/>}</label>}
createRoot(document.getElementById('root')).render(<App/>);








