export const roles=['Chief Guest','Guest of Honor','Judge','Speaker','Panellist'];
export const seed={guests:[
{id:'g1',name:'Dr. Ananya Sharma',designation:'Director of Research',organization:'Google India',email:'ananya@example.com',phone:'+91 98765 43210',expertise:['Artificial Intelligence','Research'],roles:['Chief Guest','Speaker'],available:true,color:'peach'},
{id:'g2',name:'Rahul Mehta',designation:'Co-founder & CEO',organization:'Innovate Labs',email:'rahul@example.com',phone:'+91 98765 43211',expertise:['Entrepreneurship','Product Design'],roles:['Judge','Speaker'],available:true,color:'sage'},
{id:'g3',name:'Priya Nair',designation:'Senior Product Designer',organization:'Microsoft',email:'priya@example.com',phone:'+91 98765 43212',expertise:['UX Design','Product Design'],roles:['Judge','Panellist'],available:true,color:'lavender'},
{id:'g4',name:'Prof. Vikram Rao',designation:'Professor, Computer Science',organization:'IIT Bombay',email:'vikram@example.com',phone:'+91 98765 43213',expertise:['Cybersecurity','Research'],roles:['Guest of Honor','Speaker'],available:false,color:'sand'},
{id:'g5',name:'Sneha Kapoor',designation:'Engineering Lead',organization:'Amazon',email:'sneha@example.com',phone:'+91 98765 43214',expertise:['Cloud Computing','Engineering'],roles:['Judge'],available:true,color:'rose'},
{id:'g6',name:'Arjun Desai',designation:'Founder',organization:'GreenTech Collective',email:'arjun@example.com',phone:'+91 98765 43215',expertise:['Sustainability','Entrepreneurship'],roles:['Speaker','Panellist'],available:true,color:'sky'},
{id:'g7',name:'Dr. Meera Iyer',designation:'Head of Innovation',organization:'Infosys',email:'meera@example.com',phone:'+91 98765 43216',expertise:['Artificial Intelligence','Engineering'],roles:['Judge','Speaker'],available:true,color:'peach'},
{id:'g8',name:'Karthik Reddy',designation:'Venture Partner',organization:'Seed Ventures',email:'karthik@example.com',phone:'+91 98765 43217',expertise:['Entrepreneurship','Finance'],roles:['Panellist'],available:true,color:'sage'}
],events:[{id:'e1',name:'Innovation Summit 2026',date:'2026-10-12',time:'09:00',venue:'Main Auditorium',category:'Conference',description:'Ideas that move us forward. A day of conversations, innovation, and new possibilities.',assignments:[{guestId:'g1',role:'Chief Guest',status:'Confirmed',transport:{required:true,pickup:'Kempegowda International Airport',drop:'The Oberoi, Bengaluru',time:'07:30',vehicle:'KA 01 AB 2048 · Sedan',driver:'Ramesh · 98450 12345',status:'Arranged'}},{guestId:'g2',role:'Speaker',status:'Confirmed',transport:{required:true,pickup:'Bengaluru City Railway Station',drop:'Campus Main Gate',time:'08:00',vehicle:'KA 03 CD 8910 · SUV',driver:'Suresh · 98450 54321',status:'Arranged'}},{guestId:'g3',role:'Judge',status:'Invited',transport:{required:true,pickup:'Indiranagar',drop:'Campus Main Gate',time:'08:15',vehicle:'',driver:'',status:'Not Arranged'}},{guestId:'g4',role:'Guest of Honor',status:'Confirmed',transport:{required:false,status:'Not Arranged'}},{guestId:'g5',role:'Judge',status:'Invited',transport:{required:true,pickup:'Whitefield',drop:'Campus Main Gate',time:'08:00',vehicle:'',driver:'',status:'Not Arranged'}},{guestId:'g6',role:'Panellist',status:'Declined',transport:{required:false,status:'Not Arranged'}}]},
{id:'e2',name:'Buildathon: Code for Change',date:'2026-10-24',time:'10:00',venue:'Innovation Hub',category:'Hackathon',description:'A 24-hour campus hackathon.',assignments:[{guestId:'g7',role:'Judge',status:'Invited',transport:{required:true,status:'Not Arranged'}},{guestId:'g3',role:'Judge',status:'Confirmed',transport:{required:false,status:'Not Arranged'}}]},
{id:'e3',name:'Founders & Futures',date:'2026-11-06',time:'14:00',venue:'Seminar Hall',category:'Panel discussion',description:'Meet the people building tomorrow.',assignments:[{guestId:'g8',role:'Panellist',status:'Invited',transport:{required:false,status:'Not Arranged'}}]},
{id:'e4',name:'Tech Symposium 2026',date:'2026-08-18',time:'09:30',venue:'Main Auditorium',category:'Conference',description:'Our annual technology symposium.',assignments:[{guestId:'g1',role:'Speaker',status:'Attended',transport:{required:false,status:'Completed'}},{guestId:'g2',role:'Judge',status:'Attended',transport:{required:false,status:'Completed'}},{guestId:'g4',role:'Chief Guest',status:'Attended',transport:{required:false,status:'Completed'}}]}],invitations:[]};
